### ISSUE TITLE
Getting 404 accessing with VS2017 and NuGet Package Explorer

### ISSUE THREAD

**Issue by tolemac** [giansalex/Php-Nuget-Server#1]
I'm trying to use my own installation of Php-Nuget-Server but I'm getting error accessing it:

![image](https://user-images.githubusercontent.com/247167/37815806-b274295e-2e70-11e8-8a97-f1f218538fe9.png)

It says `The V2 feed at 'blablabla' returned an unexpected status code '404 Not Found' 

The server is operative and I have uploaded some package without problems but I can read packages with Visual Studio 2017 or PackageExplorer

**Comment by giansalex** [comment]
Example:
![image](https://user-images.githubusercontent.com/14926587/37739818-7a8c5450-2d29-11e8-9e1d-281c9809b1c0.png)

**Comment by tolemac** [comment]
I understand that I have to remove `/phpnuget` segment but the result is the same.

If I navigate to http://mydom.com/phpnuget/api/v2/ I get a xml response:
![image](https://user-images.githubusercontent.com/247167/37815931-447af18e-2e71-11e8-8889-e0df659ef28a.png)

But navigating to http://mydom.com/api/v2/ I get a `Not Found` message:
![image](https://user-images.githubusercontent.com/247167/37815894-1c45b5b4-2e71-11e8-83fe-935718064628.png)

**Comment by giansalex** [comment]
For you, root nuget site is `/phpnuget/api/v2/`, 
where did you find `select package` form?

**Comment by tolemac** [comment]
Using [PME](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer), but is the same using VS 2017

**Comment by giansalex** [comment]
works for me.
![image](https://user-images.githubusercontent.com/14926587/37785966-749f8544-2dc9-11e8-8480-f9b37828b612.png)

**Comment by tolemac** [comment]
Yep, I think that I have a configuration problem.

When `/api/v2/Search()` is called `index.php` should be called, but apache search by `Search` file.

**Comment by giansalex** [comment]
you need .htaccess with correct paths

**Comment by tolemac** [comment]
Ok, I have corrected the .htaccess and works fine.

Thank you very much and congrats by your work.
