### ISSUE TITLE
[Question] I suspects this line of code

### ISSUE THREAD

**Issue by tolemac** [giansalex/Php-Nuget-Server#3]
I suspects this line of code is incorrect:

https://github.com/giansalex/Php-Nuget-Server/blob/e04dce6980e727a5db05deeaa23e8bd5fc974218/src/inc/db_nugetpackages.php#L128

I think that code:
````php
if($nugetEntity->Title==null){
	$nugetEntity->Id = "";
}
````

Have to be: 
````php
if($nugetEntity->Title==null){
	$nugetEntity->Title = "";
}
````

But I'm not sure.

**Comment by giansalex** [comment]
can you  create a pull request.'

**Comment by tolemac** [comment]
Of course!

**Comment by tolemac** [comment]
I have submit it, however I continue with the #2 problem.

I'm investigating it.
