### ISSUE TITLE
Cannot access /api/v2 without sign in

### ISSUE THREAD

**Issue by kmute90** [giansalex/Php-Nuget-Server#7]
A login dialog appears if I try to access /api/v2 (for example from Visual Studio) but cannot log in with my admin user/pass (the same works on the Sign in page)

I did a little investigation and I think there is some kind of bug in LoginController/_initialize(), because the $doLogin variable doesnt get set, so neither of the conditions get hit, and the dialog just keeps reappearing without doing anything

I commented out the auth.php in /api/v2/index.php, and now it works just fine (without authentication obviously)

**Comment by kmute90** [comment]
Also this happens (401 Unauthorized) when I'm trying to restore the packages from command line, do I have to add an apikey or something to download? i already tried that tho..

**Comment by giansalex** [comment]
Use basic authentication from command líne, pass arguments -User -Password

**Comment by kmute90** [comment]
but i cannot sign in, because my admin user/pass doesnt work somehow, if i try to access it from a browser, the dialog just keeps reappearing :(

**Comment by giansalex** [comment]
Try run setup again
